"""Build race-data.js (the deck's race chart) from data/leaderboard.jsonl. Read-only; no API calls.
Re-run after 15:00 for the final board:  python3 judges/pitch/sunday/race_sunday.py
"""
import json, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT = pathlib.Path(__file__).with_name('race-data.js')
KEEP = ['t05', 't10', 't12', 't03', 't18']

snaps, seen = [], set()
for line in open(ROOT / 'data/leaderboard.jsonl'):
    if not line.strip():
        continue
    r = json.loads(line)
    if r['tick'] in seen:
        continue
    seen.add(r['tick'])
    snaps.append(r)
snaps.sort(key=lambda r: r['tick'])

hm = lambda t: datetime.datetime.fromtimestamp(t).strftime('%a %H:%M')
series = {tm: [] for tm in KEEP}
names, days = {}, []
for i, r in enumerate(snaps):
    rk = sorted(r['teams'], key=lambda t: -t['score'])
    ids = [t['team'] for t in rk]
    day = hm(r['t'])[:3]
    if not days or days[-1][0] != day:
        days.append([day, i])
    for tm in KEEP:
        if tm in ids:
            t = rk[ids.index(tm)]
            names[tm] = t['name']
            series[tm].append([i, round(t['score'], 2), ids.index(tm) + 1])

last = snaps[-1]
rk = sorted(last['teams'], key=lambda t: -t['score'])
data = {
    'as_of': hm(last['t']), 'tick': last['tick'], 'n': len(snaps), 'days': days, 'names': names, 'series': series,
    'final': [[t['team'], t['name'], round(t['score'], 2)] for t in rk[:5]],
    'times': [hm(r['t']) for r in snaps],
}
OUT.write_text('// generated by race_sunday.py from data/leaderboard.jsonl\nwindow.RACE = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('wrote', OUT, 'as of', data['as_of'], 'tick', data['tick'], 'top5', data['final'])
